version: '3.6'

services:
  wordpress:
    image: wordpress:1337
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb:1337
    restart: always
    build: ./requirements/mariadb/
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

  nginx:
    image: nginx:1337
    container_name: nginx
    build : ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      device: /home/matef/data/WordPress
      o: bind
      type: none
  db:
    driver: local
    name: mariadb
    driver_opts:
      device: /home/matef/data/DB
      o: bind
      type: none

networks:
  inception:
    name: inception