version: '3.6'

services:
  wordpress:
    image: wordpress:13.37
    container_name: word
    ports:
      - 9000
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    container_name: maria
    image: mariadb:13.37
    restart: always
    build: ./requirements/mariadb/
    ports:
      - 3306
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

  nginx:
    image: nginx:13.37
    container_name: nginx
    build : ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: /home/matef/data/WordPress
      o: bind
      type: none
  db:
    driver: local
    driver_opts:
      device: /home/matef/data/DB
      o: bind
      type: none

networks:
  inception:
    name: inception